
-- Create a new sql
CREATE DATABASE SQL_QUIZ


-- USE SQL_QUIZ
USE SQL_QUIZ


-- CREATE TABLES
CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(45) NOT NULL,
	Surname VARCHAR(45) NOT NULL,
	Email VARCHAR(50) UNIQUE,
	CompanyId INT,
	DepartmentID SMALLINT,
	Salary DECIMAL(10,2),
	Experience TINYINT,
	StartDate DATE
)

CREATE TABLE DEPARTMENT(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Department VARCHAR(50)
)

CREATE TABLE COMPANY(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100) NOT NULL,
EstablishedDate DATE,
FieldID SMALLINT
)

CREATE TABLE FIELD(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Field VARCHAR(100) NOT NULL
)


ALTER TABLE DEPARTMENT
ADD CompanyID SMALLINT NOT NULL

ALTER TABLE EMPLOYEE
ALTER COLUMN CompanyID SMALLINT 


-- Foreign Key - Primary Key Constraints
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_Employee_Department FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(ID);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_Employee_Company FOREIGN KEY (CompanyID) REFERENCES COMPANY(ID);

ALTER TABLE COMPANY 
ADD CONSTRAINT FK_Company_Field FOREIGN KEY (FieldID) REFERENCES FIELD(ID);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT Fk_Company_Department FOREIGN KEY (CompanyID) REFERENCES COMPANY(ID)

-- SELECT FIELD TABLE
SELECT * FROM FIELD

-- INSERT SOME FIELDS
INSERT INTO FIELD(Field) VALUES('Technology') --1
INSERT INTO FIELD(Field) VALUES('Marketing') --2
INSERT INTO FIELD(Field) VALUES('R&D') --3
INSERT INTO FIELD(Field) VALUES('Industrial') --4
INSERT INTO FIELD(Field) VALUES('Biomedical') --5
INSERT INTO FIELD(Field) VALUES('Health') --6
INSERT INTO FIELD(Field) VALUES('Justice') --7
INSERT INTO FIELD(Field) VALUES('Education') --8
INSERT INTO FIELD(Field) VALUES('Finance') --9
INSERT INTO FIELD(Field) VALUES('Energy') --10
INSERT INTO FIELD(Field) VALUES('Agriculture') --11
INSERT INTO FIELD(Field) VALUES('Construction') --12
INSERT INTO FIELD(Field) VALUES('Logistics') --13
INSERT INTO FIELD(Field) VALUES('Games') --14
INSERT INTO FIELD(Field) VALUES('Commerce') --15


/* fields = [
'Technology',
'Marketing',
'R&D',
'Industrial',
'Biomedical',
'Health',
'Justice',
'Education',
'Finance',
'Energy',
'Agriculture',
'Construction'
'Logistics',
'Games',
'Commerce'

]
