
-- Create a new sql
CREATE DATABASE SQL_QUIZ


-- USE SQL_QUIZ
USE SQL_QUIZ


-- CREATE TABLES
CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(45) NOT NULL,
	Surname VARCHAR(45) NOT NULL,
	Email VARCHAR(50) UNIQUE,
	CompanyId INT,
	DepartmentID SMALLINT,
	Salary DECIMAL(10,2),
	Experience TINYINT,
	StartDate DATE
)

CREATE TABLE DEPARTMENT(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Department VARCHAR(50)
)

CREATE TABLE COMPANY(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100) NOT NULL,
EstablishedDate DATE,
FieldID SMALLINT
)

CREATE TABLE FIELD(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Field VARCHAR(100) NOT NULL
)

