
-- Create a new sql
CREATE DATABASE SQL_QUIZ


-- USE SQL_QUIZ
USE SQL_QUIZ


-- CREATE TABLES
-- USE DDL (Data Definition Language) => CREATE, DROP, ALTER, (TRUNCATE, COMMENT, RENAME etc.)
CREATE TABLE EMPLOYEE(
	ID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(45) NOT NULL,
	Surname VARCHAR(45) NOT NULL,
	Email VARCHAR(50) UNIQUE,
	CompanyId INT,
	DepartmentID SMALLINT,
	Salary DECIMAL(10,2),
	Experience TINYINT,
	StartDate DATE
)

CREATE TABLE DEPARTMENT(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Department VARCHAR(50)
)

CREATE TABLE COMPANY(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Name VARCHAR(100) NOT NULL,
EstablishedDate DATE,
FieldID SMALLINT
)

CREATE TABLE FIELD(
ID SMALLINT PRIMARY KEY IDENTITY(1,1),
Field VARCHAR(100) NOT NULL
)


ALTER TABLE DEPARTMENT
ADD CompanyID SMALLINT NOT NULL

ALTER TABLE EMPLOYEE
ALTER COLUMN CompanyID SMALLINT 


-- Foreign Key - Primary Key Constraints
ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_Employee_Department FOREIGN KEY (DepartmentID) REFERENCES DEPARTMENT(ID);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT FK_Employee_Company FOREIGN KEY (CompanyID) REFERENCES COMPANY(ID);

ALTER TABLE COMPANY 
ADD CONSTRAINT FK_Company_Field FOREIGN KEY (FieldID) REFERENCES FIELD(ID);

ALTER TABLE DEPARTMENT
ADD CONSTRAINT Fk_Company_Department FOREIGN KEY (CompanyID) REFERENCES COMPANY(ID)

-- SELECT FIELD TABLE
SELECT * FROM FIELD


SELECT *FROM COMPANY

-- ALTER TABLE
ALTER TABLE DEPARTMENT
DROP CONSTRAINT Fk_Company_Department;


ALTER TABLE DEPARTMENT
DROP COLUMN CompanyID;



-- SELECT DEPARTMENT AND INSERT SOME SAMPLES
SELECT * FROM DEPARTMENT 




-- INSERT EMPLOYEE
SELECT * FROM EMPLOYEE



USE SQL_QUIZ
SELECT * FROM EMPLOYEE


ALTER TABLE EMPLOYEE
ADD CONSTRAINT CHK_Salary CHECK(Salary>=0);

ALTER TABLE EMPLOYEE
ADD CONSTRAINT CHK_Experience CHECK(Experience >=0)

ALTER TABLE EMPLOYEE
ADD CONSTRAINT CHK_StartDate CHECK('1900-01-01'<= StartDate AND StartDate <= GETDATE())


-- SELECT * FROM COMPANY
ALTER TABLE COMPANY
ADD CONSTRAINT CHK_EstablishedDate CHECK('1850-01-01' <= EstablishedDate AND EstablishedDate <= GETDATE())



-- 